name: plant_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  flutter: ^3.1.0-0 # Kept relatively close to master channel version
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  http:
  shared_preferences: ^2.0.0-nullsafety
  url_launcher: ^6.1.1
  jwt_decoder: ^2.0.1
  url_strategy: ^0.2.0
  quiver: ^3.2.1
  path_to_regexp: ^0.4.0
  openid_client: ^0.4.8
  dual_screen: ^1.0.4
  sizer: ^2.0.15
  flutter_spinkit: ^5.2.1
  adaptive_breakpoints: ^0.1.7
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Electrolize
      fonts:
        - asset: fonts/Electrolize-Regular.ttf

  assets:
    - assets/images/
    - assets/images/tropical_plants/
    - assets/images/aquatic_plants/
    - assets/images/epified_plants/
    - assets/images/moss/
    - assets/config/dev.json
    - assets/config/prod.json
